black_sheep_music_library_api:
    resource: '@BlackSheepUserBundle/Controller/Api'
    type:     annotation
    prefix:   /api/
black_sheep_user_homepage:
    path:     /you
    defaults: { _controller: BlackSheepUserBundle:Profile:index }
black_sheep_user_profile_edit:
    path:     /edit
    defaults: { _controller: BlackSheepUserBundle:Profile:edit }
