services:
    BlackSheep\UserBundle\Controller\Api\ApiProfileController:
        class: BlackSheep\UserBundle\Controller\Api\ApiProfileController
        arguments: ['@event_dispatcher', '@fos_user.profile.form.factory', '@fos_user.user_manager', '@fos_user.email_update_confirmation', '@translator']

