fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: BlackSheep\User\Entity\SheepUser
    from_email:
        address: 'slurpie@gmail.com'
        sender_name: BlackSheepMusic
    registration:
        confirmation:
            enabled: true
