fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        sheepmusic_artists:
            index_name: sheepmusic_artists_%kernel.environment%
            settings:
                number_of_shards: 1
                index:
                    analysis:
                        analyzer:
                          custom_analyzer :
                            type     :    custom
                            tokenizer:    nGram
                            filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, ngram, my_metaphone]
                          custom_search_analyzer :
                            type     :    custom
                            tokenizer:    nGram
                            filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, nGram, my_metaphone]
                        tokenizer:
                          nGram:
                            type:     nGram
                            min_gram: 3
                            max_gram: 3
                        filter:
                          snowball:
                            type:     snowball
                            language: English
                          elision:
                            type:     elision
                            articles: [l, m, t, qu, n, s, j, d]
                          stopwords:
                            type:      stop
                            stopwords: [_english_]
                            ignore_case : true
                          worddelimiter :
                            type:      word_delimiter
                          my_metaphone :
                            type: phonetic
                            encoder: metaphone
                            replace: false
            types:
                artist:
                    properties:
                        name:
                            type: text
                            analyzer : custom_analyzer
                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: BlackSheep\MusicLibrary\Entity\ArtistsEntity
                        finder: ~
                        provider: ~
                        listener:
                            defer: true
        sheepmusic_albums:
            index_name: sheepmusic_albums_%kernel.environment%
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer:
                                type:    custom
                                tokenizer:    nGram
                                filter:    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, ngram, my_metaphone]
                            custom_search_analyzer:
                                type:    custom
                                tokenizer:    nGram
                                filter:    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, nGram, my_metaphone]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 3
                        filter:
                            snowball:
                                type:     snowball
                                language: English
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case: true
                            worddelimiter:
                                type:      word_delimiter
                            my_metaphone:
                                type: phonetic
                                encoder: metaphone
                                replace: false
            types:
                album:
                    properties:
                        name:
                            type: text
                            analyzer : custom_analyzer
                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: BlackSheep\MusicLibrary\Entity\AlbumEntity
                        finder: ~
                        provider: ~
                        listener:
                            defer: true
        sheepmusic_songs:
            index_name: sheepmusic_songs_%kernel.environment%
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer:
                                type:    custom
                                tokenizer:    nGram
                                filter:    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, ngram, my_metaphone]
                            custom_search_analyzer:
                                type:    custom
                                tokenizer:    nGram
                                filter:    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter, nGram, my_metaphone]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 3
                        filter:
                            snowball:
                                type:     snowball
                                language: English
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case: true
                            worddelimiter:
                                type:      word_delimiter
                            my_metaphone:
                                type: phonetic
                                encoder: metaphone
                                replace: false
            types:
                song:
                    properties:
                        title:
                            type: text
                            analyzer : custom_analyzer
                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: BlackSheep\MusicLibrary\Entity\SongEntity
                        finder: ~
                        provider: ~
                        listener:
                            defer: true
