# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BlackSheep\User\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        jwt:
            lexik_jwt:
                class: BlackSheep\User\Entity\User
        # used to reload user from session & other features (e.g. switch_user)
        blacksheep_user_provider:
            entity:
                class: BlackSheep\User\Entity\User
                property: username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
            provider: jwt
        login:
            provider: blacksheep_user_provider
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            guard:
                authenticators:
                    - BlackSheep\User\Security\FormLoginAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
        api:
            logout: true
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: blacksheep_user_provider
            guard:
                authenticators:
                    - BlackSheep\User\Security\Guard\JWTTokenAuthenticator
        song:
            pattern:  ^/song
            stateless: true
            anonymous: false
            provider: jwt
            guard:
                authenticators:
                    - BlackSheep\User\Security\Guard\JWTTokenAuthenticator

    access_control:
        - { path: ^/song/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/*, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
