services:
    BlackSheep\MusicBrainz\EventListener\AlbumEventSubscriber:
        arguments:
            - '@BlackSheep\MusicBrainz\Updater\AlbumUpdater'
        tags:
            - { name: kernel.event_subscriber }
