services:
    black_sheep_music_scanner.services.media_importer:
        class: 'BlackSheep\MusicScannerBundle\Services\MediaImporter'
        public: true
        arguments:
            - '@doctrine'
            - '@black_sheep_music_scanner.services.song_importer'

    black_sheep_music_scanner.services.song_importer:
        class: 'BlackSheep\MusicScannerBundle\Services\SongImporter'
        public: true
        arguments:
            - '@doctrine'
            - '@black_sheep_music_scanner.services.album_importer'
            - '@black_sheep_music_scanner.services.artist_importer'

    black_sheep_music_scanner.services.album_importer:
        class: 'BlackSheep\MusicScannerBundle\Services\AlbumImporter'
        public: true
        arguments:
            - '@doctrine'
            - '@black_sheep_music_library.last_fm.last_fm_album'

    black_sheep_music_scanner.services.artist_importer:
        class: 'BlackSheep\MusicScannerBundle\Services\ArtistImporter'
        public: true
        arguments:
            - '@doctrine'
            - '@black_sheep_music_library.last_fm.last_fm_artist'
