black_sheep_music_scanner_library:
    resource: "@BlackSheepMusicScanner/Controller"
    type:     annotation
black_sheep_music_library:
    resource: '@BlackSheepMusicLibrary/Resources/config/routing.yml'
black_sheep_user:
    resource: "@BlackSheepUser/Resources/config/routing.yml"
black_sheep_last_fm:
    resource: "@BlackSheepLastFm/Resources/config/routing.yml"
