nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    '^/api/':
        allow_origin: ['*']
        expose_headers: ['Authorization']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH']
        max_age: 3600
    '^/':
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600
        hosts: ['^api\.']
    '^/play':
        origin_regex: true
        allow_origin: ['*']
        allow_headers: ['Access-Control-Allow-Origin']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600
