api_login_check:
    path: /api/login_check
black_sheep_music_scanner_library:
    resource: "@BlackSheepMusicScannerBundle/Controller"
    type:     annotation
black_sheep_music_library:
    resource: '@BlackSheepMusicLibraryBundle/Resources/config/routing.yml'
black_sheep_user:
    resource: "@BlackSheepUserBundle/Resources/config/routing.yml"
black_sheep_last_fm:
    resource: "@BlackSheepLastFmBundle/Resources/config/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }



