# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    token_authenticator:
            class: BlackSheep\UserBundle\Security\TokenAuthenticator
            arguments: ['@lexik_jwt_authentication.encoder', '@doctrine.orm.entity_manager']
