black_sheep_music_library_song:
    resource: "@BlackSheepMusicLibrary/Controller/SongController.php"
    type:     annotation
black_sheep_music_library_api:
    resource: '@BlackSheepMusicLibrary/Controller/Api'
    type:     annotation
    prefix:   /api/
