services:
    black_sheep_music_library.last_fm.last_fm_artist:
        class: BlackSheep\MusicLibrary\LastFm\LastFmArtist
        arguments:
            - '@black_sheep.last_fm.last_fm_artist_info'
    black_sheep_music_library.last_fm.last_fm_album:
        class: BlackSheep\MusicLibrary\LastFm\LastFmAlbum
        arguments:
            - '@black_sheep.last_fm.last_fm_album_info'
