services:
    black_sheep.music_library.artwork.factory:
        class: BlackSheep\MusicLibrary\Factory\ArtworkFactory
        arguments:
            - '@vich_uploader.upload_handler'
            - '%kernel.root_dir%'
