services:
    black_sheep_musicbrainz.album_event_subscriber:
        class: BlackSheep\MusicBrainzBundle\EventListener\AlbumEventSubscriber
        arguments:
            - '@black_sheep_musicbrainz.album_updater'
        tags:
            - { name: kernel.event_subscriber }
    black_sheep_musicbrainz.album_updater:
            class: BlackSheep\MusicBrainzBundle\Updater\AlbumUpdater
            arguments:
                - '@black_sheep_music_library.repository.albums_repository'
                - '@black_sheep_musicbrainz.client.release_client'
    black_sheep_musicbrainz.client.release_client:
            class: BlackSheep\MusicBrainzBundle\Client\ReleaseClient
