# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $ffmpegPath: "%black_sheep_music_library.ffmpeg_path%"
            $ffprobePath: "%black_sheep_music_library.ffprobe_path%"
            $bitrate: "%black_sheep_music_library.bitrate%"
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    BlackSheep\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    BlackSheep\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    black_sheep_music_scanner.services.media_importer:
        alias: BlackSheep\MusicScanner\Services\MediaImporter
        public: true

    black_sheep_music_scanner.services.song_importer:
        alias: BlackSheep\MusicScanner\Services\SongImporter
        public: true

    black_sheep_music_scanner.services.album_importer:
        alias: BlackSheep\MusicScanner\Services\AlbumImporter
        public: true

    black_sheep_music_scanner.services.artist_importer:
        alias: BlackSheep\MusicScanner\Services\ArtistImporter
        public: true

    token_authenticator:
        class: BlackSheep\User\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder', '@doctrine.orm.entity_manager']
