services:
    black_sheep_fanart_tv.artist_event_subscriber:
            class: BlackSheep\FanartTvBundle\EventListener\ArtistEventSubscriber
            arguments:
                - '@black_sheep_fanart_tv.artist_updater'
            tags:
                - { name: kernel.event_subscriber }
    black_sheep_fanart_tv.album_updater:
        class: BlackSheep\FanartTvBundle\Updater\AlbumUpdater
        arguments:
            - '@black_sheep_music_library.repository.albums_repository'
            - '@black_sheep_fanart_tv.client.music_client'
            - '@black_sheep.music_library.artwork.factory'
    black_sheep_fanart_tv.artist_updater:
                class: BlackSheep\FanartTvBundle\Updater\ArtistUpdater
                arguments:
                    - '@black_sheep_music_library.repository.artists_repository'
                    - '@black_sheep_fanart_tv.client.music_client'
                    - '@black_sheep.music_library.artwork.factory'
    black_sheep_fanart_tv.client.music_client:
        class: BlackSheep\FanartTvBundle\Client\MusicClient
