<?php
namespace BlackSheep\MusicLibraryBundle\Repository;

use BlackSheep\MusicLibraryBundle\Entity\Artists;
use Doctrine\ORM\EntityRepository;

/**
 * SongsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{

    /**
     * @param $artistName
     * @return Artists|null
     */
    public function addOrUpdateByName($artistName)
    {
        $entityManager = $this->getEntityManager();
        $artistEntity = $this->findOneBy(
            ['name' => $artistName]
        );
        if ($artistEntity === null ||
            ($artistEntity instanceof Artists) === false) {
            $artistEntity = Artists::createNew($artistName);
            $entityManager->persist($artistEntity);
            $entityManager->flush($artistEntity);
        }
        return $artistEntity;
    }

    /**
     * @param Artists $artist
     * @param $albumName
     * @return null|object
     */
    public function getArtistAlbumByName(Artists $artist, $albumName)
    {
        return $this->findOneBy(
            ['id' => $artist->getId(),'albums.name' => $albumName]
        );
    }
}
