<?php
namespace BlackSheep\MusicLibraryBundle\Repository;

use BlackSheep\MusicLibraryBundle\Entity\Songs;
use Doctrine\ORM\EntityRepository;

/**
 * SongsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongsRepository extends EntityRepository
{

    /**
     * @param $songInfo
     * @return null|Songs
     */
    public function needsImporting($songInfo)
    {
        return $this->findOneBy(['mTime' => $songInfo['mTime'], 'path' => $songInfo['path']]);
    }
}
