<?php

namespace BlackSheep\MusicLibraryBundle\Repository;

use BlackSheep\MusicLibraryBundle\Entity\SongEntity;
use Doctrine\ORM\EntityRepository;

/**
 * SongsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongsRepository extends AbstractRepository implements SongsRepositoryInterface
{
    /**
     * @param $songInfo
     *
     * @return null|SongEntity
     */
    public function needsImporting($songInfo)
    {
        return $this->findOneBy(['mTime' => $songInfo['mTime'], 'path' => $songInfo['path']]);
    }
}
